nginx:
  container_name: nginx
  build: .
  dockerfile: Dockerfile-nginx
  links:
    - node1:node1
    - node2:node2
    - node3:node3
  ports:
    - "80:80"
    - "443:443"
node1:
  container_name: node-codewithdan-1
  build: .
  dockerfile: Dockerfile-node-codewithdan
  ports:
   - "8080"
  volumes:
    - .:/var/www/codewithdan
  working_dir: /var/www/codewithdan
  links:
   - mongo
   - redis
node2:
  container_name: node-codewithdan-2
  build: .
  dockerfile: Dockerfile-node-codewithdan
  ports:
   - "8080"
  volumes:
    - .:/var/www/codewithdan
  working_dir: /var/www/codewithdan
  links:
   - mongo
   - redis
node3:
  container_name: node-codewithdan-3
  build: .
  dockerfile: Dockerfile-node-codewithdan
  ports:
   - "8080"
  volumes:
    - .:/var/www/codewithdan
  working_dir: /var/www/codewithdan
  links:
   - mongo
   - redis
mongo:
  container_name: mongo
  build: .
  dockerfile: Dockerfile-mongo
  ports:
   - "27017:27017"
  env_file:
    - ./.docker/secrets.env
  volumes:
    - /data/db:/data/db
redis:
  container_name: redis
  build: .
  dockerfile: Dockerfile-redis
  ports:
    - "6379"